export const UI_STRINGS_EN = {
  'nav.home': 'Home',
  'nav.about': 'About',
  'nav.ministries': 'Ministries',
  'nav.sermons': 'Sermons',
  'nav.events': 'Events & News',
  'nav.discipleship': 'Discipleship Library',
  'nav.prayer': 'Prayer',
  'nav.give': 'Give',
  'nav.contact': 'Contact',
  'nav.portal': 'Member Portal',
  'nav.join': 'Join Us',
  'nav.signIn': 'Sign In',
  'nav.signOut': 'Sign Out',
  'nav.admin': 'Admin',
  'library.title': 'Discipleship Library',
  'library.subtitle': 'Courses, devotionals, Bible studies, and training resources.',
  'library.today': "Today's Daily Notice",
  'library.search': 'Search materials, speakers, topics...',
  'library.all': 'All',
  'library.read': 'Read',
  'library.listen': 'Listen',
  'library.watch': 'Watch',
  'library.save': 'Save',
  'library.complete': 'Mark complete',
  'library.download': 'Download',
  'library.share': 'Share',
  'portal.welcome': 'Welcome',
  'portal.todayBite': "Today's Teaching",
  'portal.myCourses': 'My Courses',
  'portal.myLibrary': 'My Library',
  'portal.events': 'Events',
  'portal.giving': 'Giving',
  'media.library': 'Sermons',
  'common.loading': 'Loading...',
  'common.language': 'Language',
  'common.aiTranslated': 'AI translated',
  'home.dailyNotice': 'Daily Notice',
}
