export const UI_STRINGS_EN = {
  'nav.home': 'Home',
  'nav.about': 'About',
  'nav.live': 'Live',
  'nav.discipleship': 'Discipleship',
  'nav.media': 'Media',
  'nav.prayer': 'Prayer',
  'nav.portal': 'Portal',
  'nav.support': 'Support',
  'nav.join': 'Join Now',
  'nav.signIn': 'Sign In',
  'nav.signOut': 'Sign Out',
  'nav.admin': 'Admin',
  'nav.ministries': 'Ministries',
  'library.title': 'Discipleship Library',
  'library.subtitle': 'Daily spiritual materials, courses, devotionals, and training resources.',
  'library.today': "Today's Spiritual Material",
  'library.search': 'Search materials, speakers, topics...',
  'library.all': 'All',
  'library.read': 'Read',
  'library.listen': 'Listen',
  'library.watch': 'Watch',
  'library.save': 'Save',
  'library.complete': 'Mark complete',
  'library.download': 'Download',
  'library.share': 'Share',
  'portal.welcome': 'Welcome back',
  'portal.todayBite': "Today's Daily Christ Bite",
  'portal.growthTrack': 'Growth Track',
  'portal.myCourses': 'My Courses',
  'media.library': 'Media Library',
  'media.trending': 'Trending Now',
  'live.nowStreaming': 'Now Streaming',
  'live.watchNow': 'Watch Live Now',
  'common.loading': 'Loading...',
  'common.language': 'Language',
  'common.aiTranslated': 'AI translated',
}
